### ISSUE TITLE
hostpath-provisioner `arm64` container image contains wrong build of `hostpath-provisioner`

### ISSUE THREAD

**Issue by anjannath** [kubevirt/hostpath-provisioner#139]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

the `linux/arm64` image at `quay.io/kubevirt/hostpath-provisioner:latest` contains `amd64` executable of `host-provisioner`

**What you expected to happen**:
the `linux/arm64` image  should contain the `arm64` executable of `host-provisioner`

**How to reproduce it (as minimally and precisely as possible)**:

Try to run `podman run --rm -it quay.io/kubevirt/hostpath-provisioner:latest` on an `arm` machine

```bash
$ arch
aarch64

$ podman run --rm -it quay.io/kubevirt/hostpath-provisioner
exec /hostpath-provisioner: exec format error

# actually checking the executable reveals its built for amd64
$ podman image mount quay.io/kubevirt/hostpath-provisioner
/var/lib/containers/storage/overlay/fcc8ef11bab806908c78d015004a6ea64c5204bf52f49a305e15d69925ded60a/merged

$ file /var/lib/containers/storage/overlay/fcc8ef11bab806908c78d015004a6ea64c5204bf52f49a305e15d69925ded60a/merged/hostpath-provisioner
/var/lib/containers/storage/overlay/fcc8ef11bab806908c78d015004a6ea64c5204bf52f49a305e15d69925ded60a/merged/hostpath-provisioner: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
```

**Comment by maya-r** [comment]
Note that even when these PRs will merge, the job only publishes images when there's a release tagged.
Perhaps @awels can tag a release after they are merged

**Comment by anjannath** [comment]
@maya-r @awels can you please look into this, the image at `http://registry.redhat.io/container-native-virtualization/hostpath-csi-driver-rhel8:v4.11.0` also seems to be missing arm
