### ISSUE TITLE
provider hostpath-provisioner official chart

### ISSUE THREAD

**Issue by wl-chen** [kubevirt/hostpath-provisioner#142]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind enhancement

**What happened**:

**What you expected to happen**:
In my scene, i need a hostpath-provisioner chart to support hostpath storage, but i cant find an official chart. Is it possible to provide a hostpath-provisioner chart？

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by awels** [comment]
When you say 'chart' what do you mean? A helm chart?

**Comment by wl-chen** [comment]
> When you say 'chart' what do you mean? A helm chart?

yes, a helm chart~

**Comment by Tcharl** [comment]
I do not think that a CSI is installed through helm...
It's an operator

**Comment by wl-chen** [comment]
> I do not think that a CSI is installed through helm... It's an operator

I mean that yaml files that located in dir /deploy/csi can be modified into a helm chart. Also nfs (https://artifacthub.io/packages/helm/nfs-subdir-external-provisioner/nfs-subdir-external-provisioner) and ceph-fs (https://artifacthub.io/packages/helm/ceph-csi/ceph-csi-cephfs) both have their own official chart.

**Comment by awels** [comment]
Right we don't produce a helm chart, there is an operator located at github.com/kubevirt/hostpath-provisioner-operator that has all the details needed to install kubevirt hostpath provisioner. Now I am not opposed to having a helm chart as well, I just never made one, so I am not up on the details on what to do there. If you would like one feel free to open a PR
