### ISSUE TITLE
Adding power support for "https://quay.io/repository/kubevirt/hostpath-csi-driver"

### ISSUE THREAD

**Issue by ghatwala** [kubevirt/hostpath-provisioner#203]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind enhancement

We are attempting to install single node cluster(SNC) on ibm power(ppc64le) platform and to do so we need this image - https://quay.io/repository/kubevirt/hostpath-csi-driver?tab=tags&tag=latest to be power supported too. 
The image in invoked here - https://github.com/crc-org/snc/blob/master/kubevirt-hostpath-provisioner-csi/csi-driver/kustomization.yaml#L4.

Was able to build this image locally on a power node using below.
```
hostpath-provisioner] # make image-csi
./hack/build-csi.sh
buildah build --platform linux/ppc64le -t quay.io/kubevirt/hostpath-csi-driver:ppc64le -f Dockerfile.csi .
STEP 1/3: FROM registry.fedoraproject.org/fedora-minimal:34
STEP 2/3: COPY _out/hostpath-csi-driver /
STEP 3/3: ENTRYPOINT ["/hostpath-csi-driver"]
COMMIT quay.io/kubevirt/hostpath-csi-driver:ppc64le
Getting image source signatures
Copying blob 0e6916f70223 skipped: already exists
Copying blob bef3308d1e4d done
Copying config 3a42318334 done
Writing manifest to image destination
Storing signatures
--> 3a423183348
[Warning] one or more build args were not consumed: [TARGETARCH TARGETOS TARGETPLATFORM]
Successfully tagged quay.io/kubevirt/hostpath-csi-driver:ppc64le
using only below change.

hostpath-provisioner] # git diff
diff --git a/Makefile b/Makefile
index b044826..ffa3950 100644
--- a/Makefile
+++ b/Makefile
@@ -22,7 +22,7 @@ DOCKER_REPO?=quay.io/kubevirt
 ARTIFACTS_PATH?=_out
 GOLANG_VER?=1.19.4
 GOOS?=linux
-GOARCH?=amd64
+GOARCH?=ppc64le
 BUILDAH_PLATFORM_FLAG?=--platform $(GOOS)/$(GOARCH)
 OCI_BIN ?= $(shell if podman ps >/dev/null 2>&1; then echo podman; elif docker ps >/dev/null 2>&1; then echo docker; fi)
images built ...

hostpath-provisioner] # podman images | grep kubevirt
quay.io/kubevirt/hostpath-csi-driver                                                               ppc64le                                 3a4231833481  37 seconds ago  181 MB
quay.io/kubevirt/hostpath-provisioner                                                              ppc64le                                 7b55cc467f49  30 minutes ago  216 MB
```
Wanted to know thoughts/comments about how to enable power(ppc64le arch) support for this image - https://quay.io/repository/kubevirt/hostpath-csi-driver?tab=tags&tag=latest ?

**Comment by awels** [comment]
https://github.com/kubevirt/project-infra/pull/2827 will add the arch to the release. Once that is in, I can make a new release that hopefully should contain the container you want.

**Comment by ghatwala** [comment]
thanks a lot for the quick fix @awels  !!!
FYI @praveenkumar @mtarsel - we should have power support for `hostpath-csi-driver` image hopefully soon. .

**Comment by ghatwala** [comment]
thanks @awels  can see `ppc64le` supported - https://quay.io/repository/kubevirt/hostpath-csi-driver?tab=tags&tag=latest

**Comment by awels** [comment]
Thats the nightly I think, I am still working through some issues before being able to make an official release. Let me know if the nightly works for you.

**Comment by ghatwala** [comment]
Will wait for official release ...

**Comment by awels** [comment]
So I tried making a release and I have some issue with the release process that I haven't gotten around to fixing. Sorry for the delay.

**Comment by ghatwala** [comment]
hi @awels  just checking - seems release process hasn't been fixed yet ?? only nightly has power support here - https://quay.io/repository/kubevirt/hostpath-csi-driver?tab=tags&tag=latest

**Comment by awels** [comment]
Yes sorry I have been really busy with other things and haven't gotten around to fixing the issue. It is on my list though

**Comment by awels** [comment]
Okay I managed to find some time to fix it. There is now a 0.17 release available that includes ppc containers. https://quay.io/repository/kubevirt/hostpath-provisioner?tab=tags

**Comment by ghatwala** [comment]
thanks a lot - @awels  !!!

**Comment by ghatwala** [comment]
Closing issue as power arch support has been added  - https://github.com/kubevirt/hostpath-provisioner/issues/203#issuecomment-1640713235
