### ISSUE TITLE
extensions removal in 1.16

### ISSUE THREAD

**Issue by j-griffith** [kubevirt/hostpath-provisioner#36]
/kind bug

**What happened**:

Using `kubectl apply -f https://raw.githubusercontent.com/kubevirt/hostpath-provisioner/master/deploy/kubevirt-hostpath-provisioner.yaml` no longer works for Kubernetes versions >= 1.16 because the existensions api is no longer used.

Instead, on the extensions api is replaced with the apps api.  

More info on the removal in 1.16 can be found here:  https://github.com/kubernetes/kubernetes/issues/84782

**What you expected to happen**:

kubectl apply should install the provisioner

**How to reproduce it (as minimally and precisely as possible)**:

Use a current upstream k8s version (1.17) and run kubectl apply of the deployment manifest

**Comment by awels** [comment]
Hi, yeah give me a minute to update the yaml with the apps api.

**Comment by j-griffith** [comment]
> Hi, yeah give me a minute to update the yaml with the apps api.

I actually have a fix on the way if you want it... but if you'd rather submit yourself that's cool

**Comment by awels** [comment]
No go ahead, I am fixing some other stuff right now. Btw if you install with the operator you should have this issue :)

**Comment by j-griffith** [comment]
Operators.. ha!

**Comment by awels** [comment]
https://github.com/kubevirt/hostpath-provisioner-operator :)
