### ISSUE TITLE
Feature request: Allow more access modes than ReadWriteOnce

### ISSUE THREAD

**Issue by codeclown** [kubevirt/hostpath-provisioner#66]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:

I haven't tested it, but based on the title of https://github.com/kubevirt/hostpath-provisioner/pull/40 which is "HPP only supports ReadWriteOnce"...

Only `accessModes: ['ReadWriteOnce']` is supported.

**What you expected to happen**:

Pods on the same node are able to read from and write into the same path, so it should be possible to use e.g. `ReadWriteMany`.

Correct me if I'm wrong, but I assume the reason for this limitation is that users might try to mount a volume into multiple pods that exist on separate nodes.

If this is the only reason, I think it's still reasonable to allow using e.g. ReadWriteMany, because users are already able to use annotations to control which node the volume is created on, and related pods can simply be created on the same node.

My usecase for this is even simpler: using hostpath on a single-node cluster.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

**Comment by awels** [comment]
The semantics of access modes are on a node level, so ReadWriteOnce is a node level, there is nothing stopping you from creating 2 pods on the same node using a RWO PV. RWX is for accessing the volume on multiple nodes. Which is not possible for hostpath provisioner since it is a local storage.

**Comment by codeclown** [comment]
Oh, that's a brainfart by me... thank you for the swift reply, and for the great library!
