### ISSUE TITLE
kubevirt use hostplugin to add volume use host-provisioner

### ISSUE THREAD

**Issue by mzzgaopeng** [kubevirt/hostpath-provisioner#67]
Hi
This problem was encountered when we used kubevirt local disk,
When I use the local disk, 
When using hot-mounted disks, the hot-mounted disk type needs to be local instead of hostpath in kubevirt's disk addition logic, otherwise the disk cannot be mounted.

But the PV types created in hostpath-provisioner are all hostpaths. I want to know if the kubevirt community has created a local-provisioner to create PV types to support local, or other solutions.

**Comment by awels** [comment]
I don't understand why you are saying this hotplugging is supported for both hostpath and local volume PVs. But there is a local volume provisioner that is released by kubernetes.

**Comment by mzzgaopeng** [comment]
> I don't understand why you are saying this hotplugging is supported for both hostpath and local volume PVs. But there is a local volume provisioner that is released by kubernetes.

I found the hotplug method  , but the strongclasses we use is hostpath-provisioner, but the type of persistentvolume created by this strongclasses is hostpath, not the local type supported by kubevirt hotplug.



exp:

apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  capacity:
    storage: 100Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disks/ssd1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - example-node

**Comment by mzzgaopeng** [comment]
> I don't understand why you are saying this hotplugging is supported for both hostpath and local volume PVs. But there is a local volume provisioner that is released by kubernetes.

I found the hotplug method  , but the strongclasses we use is hostpath-provisioner, but the type of persistentvolume created by this strongclasses is hostpath, not the local type supported by kubevirt hotplug.



exp:

apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disks/ssd1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - example-node

**Comment by awels** [comment]
I am saying KubeVirt supports hotplugging hostpath volumes (I know. since I wrote the code that does it) The PR that adds the support is https://github.com/kubevirt/kubevirt/pull/5088

**Comment by mzzgaopeng** [comment]
Thanks
I confirmed that this merged was finally merged into the matser branch, and it was finally 0.40 when kubevirt was released.

**Comment by mzzgaopeng** [comment]
> 我说的是KubeVirt支持热插拔主机路径卷（我知道。因为我编写了这样做的代码），添加支持的PR是[kubevirt / kubevirt＃5088](https://github.com/kubevirt/kubevirt/pull/5088)

Thanks，
I confirmed that this merged was finally merged into the matser branch, and it was finally 0.40 when kubevirt was released.

**Comment by awels** [comment]
Feel free to close this issue, as this provisioner will only ever create hostpath pvs.

**Comment by mzzgaopeng** [comment]
thanks
