### ISSUE TITLE
Publish the images on quay or dockerhub

### ISSUE THREAD

**Issue by Tcharl** [kubevirt/hostpath-provisioner#71]
**FEATURE REQUEST**:

/kind enhancement

**What happened**:
Hi Community, thank you very much for that marvelous CSI hostpath providers!
didn't try it but took a look at the code, and I would never succeed to achieve that.

Now, here's my setup:
I have kube with multiple nodes (either VMs or bare metal) which are managed by an IDM (freeipa) and where some NFS mountpoints are identical on each nodes (with IPA automount and krb5p).
Thus I'm seeing a huge value in this csi provider now to have kinda cloud storage through mounted (kerberized) nfs!

Leading to my request: would it be possible to release the two container image to one hub (quay or docker) so that identic topologies will be able to work?
Otherwise, there's a chicken and egg issue: creating a container registry in a kube cluster instance to host the provisionner containers requires a pv, which can't be provisionned using the provisionner....

**Comment by Tcharl** [comment]
Already done, sry for the inconvenience

**Comment by Tcharl** [comment]
Reopening, as the csi is not yet published

**Comment by awels** [comment]
Hi, yes I am working on this, including a proper operator to easily deploy. I am currently on PTO, but it should be soonish.

**Comment by awels** [comment]
Hi, just managed to get the publishing system to work. The csi driver container can be found here: https://quay.io/repository/kubevirt/hostpath-csi-driver?tab=tags and the legacy provisioner can be found here: https://quay.io/repository/kubevirt/hostpath-provisioner?tab=tags

**Comment by awels** [comment]
I will hopefully do an official release soon, need to do some operator work to get it all sorted.
