### ISSUE TITLE
support for ReadWriteMany

### ISSUE THREAD

**Issue by tommymalmqvist** [kubevirt/hostpath-provisioner#72]
**FEATURE REQUEST:**

/kind enhancement

**What happened:**

Hello,

The company that I'm at have our own software that will replicate data between nodes and it would be really nice if I could use hostpath-provisioner in ReadWriteMany.

Best regards

**Comment by awels** [comment]
So I have been trying to work out how I could support RWX in hostpath. And the only way this would work if the underlying hostpath directory used is mounted on multiple nodes. So lets say I have some shared storage (NFS for instance) that is mounted in /mnt/shared/ and the hostpath directory configured is set to /mnt/shared/hostpath. Then I could make RWX hostpath volumes that point to /mnt/shared/hostpath/<volume>

There are certainly details to work out for this but I have this on the TODO list for the provisioner. Most likely won't get to this until I finish with the CSI imlementation

**Comment by tommymalmqvist** [comment]
Hi @awels, that is exactly what I'm looking for.

Good to know that it is on the TODO list for the provisioner.

**Comment by awels** [comment]
So RWO PVs work just fine on a single node with multiple pods. You should not have to patch anything and just create a second pod with the same PVC. Should just work. See https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes for the definition in particular `the volume can be mounted as read-write by a single node. ReadWriteOnce access mode still can allow multiple pods to access the volume when the pods are running on the same node.`

**Comment by Tcharl** [comment]
> So I have been trying to work out how I could support RWX in hostpath. And the only way this would work if the underlying hostpath directory used is mounted on multiple nodes. So lets say I have some shared storage (NFS for instance) that is mounted in /mnt/shared/ and the hostpath directory configured is set to /mnt/shared/hostpath. Then I could make RWX hostpath volumes that point to /mnt/shared/hostpath/

This is my setup!

**Comment by aglitke** [comment]
If your backing storage is NFS then it might make more sense to use the NFS CSI driver directly instead of HPP.  I am going to close this issue but feel free to reopen if you would like to continue pursuing this RFE.

**Comment by Tcharl** [comment]
@aglitke Unfortunately the NFS CSI driver doesn't seem to support krb5x, which is a must on my side (I'm on a hostile, all nodes public environment): this driver, as it is relying on linux mounts (low level) seems to be a much more elegant solution (it's relying on something that is proven to work and gets the benefits of tenth of years of code ;-)).
It's my only opinion and requirement, but I totally understand that it could be considered as an edge case.

Best regards,
