### ISSUE TITLE
CSI plugin accepts `--version`, not `--v`, so Daemonset will fail to start 

### ISSUE THREAD

**Issue by aw185176** [kubevirt/hostpath-provisioner#76]
```
I0923 23:40:19.117632       1 plugin.go:42] Starting new HostPathDriver, config: {hostpath.csi.kubevirt.io unix://csi/csi.sock gke-dev-infra2-dev-infra-ci-worker-po-59d79db6-p0l9 /csi-data-dir  <nil>}
I0923 23:40:19.117715       1 plugin.go:45] Failed to initialize driver: no version provided
```

**Comment by awels** [comment]
Yes, you can add --version=latest or something to the daemonset to make it work. I am in the middle of a rework to the csi driver, so I haven't updated all the different details yet, like the deployment yaml. I will get to it soon.

**Comment by aw185176** [comment]
No worries, I got everything working yesterday, just figured I would drop issues for the pieces I had to update
